/* =========================================================
   ARDANA BATIK
   DATABASE SCHEMA
   Junior Web Developer - Sertifikasi
========================================================= */


/* =========================================================
   1. PRODUCTS
========================================================= */

create table if not exists public.products (

    id bigint generated by default as identity
        primary key,

    name text not null,

    description text,

    price numeric(12, 2)
        not null
        default 0,

    image_url text,

    category text not null,

    stock integer
        not null
        default 0,

    created_at timestamptz
        not null
        default now()

);


/* =========================================================
   2. PROFILES
========================================================= */

create table if not exists public.profiles (

    id uuid
        primary key
        references auth.users(id)
        on delete cascade,

    full_name text,

    role text
        not null
        default 'user',

    created_at timestamptz
        not null
        default now(),

    constraint profiles_role_check
        check (
            role in ('user', 'admin')
        )

);


/* =========================================================
   3. ORDERS
========================================================= */

create table if not exists public.orders (

    id bigint generated by default as identity
        primary key,

    order_number text
        not null
        unique,

    customer_name text
        not null,

    phone text
        not null,

    notes text,

    total numeric(12, 2)
        not null
        default 0,

    status text
        not null
        default 'pending',

    user_id uuid
        references auth.users(id)
        on delete set null,

    created_at timestamptz
        not null
        default now(),

    constraint orders_status_check
        check (
            status in (
                'pending',
                'processing',
                'completed',
                'cancelled'
            )
        )

);


/* =========================================================
   4. ORDER ITEMS
========================================================= */

create table if not exists public.order_items (

    id bigint generated by default as identity
        primary key,

    order_id bigint
        not null,

    product_id bigint
        not null,

    product_name text
        not null,

    price numeric(12, 2)
        not null
        default 0,

    quantity integer
        not null
        default 1,

    subtotal numeric(12, 2)
        not null
        default 0,

    created_at timestamptz
        not null
        default now(),

    constraint order_items_order_id_fkey
        foreign key (order_id)
        references public.orders(id)
        on delete cascade,

    constraint order_items_product_id_fkey
        foreign key (product_id)
        references public.products(id)
        on delete restrict,

    constraint order_items_quantity_check
        check (
            quantity > 0
        )

);


/* =========================================================
   5. INDEX
========================================================= */

create index if not exists idx_products_category
on public.products(category);


create index if not exists idx_products_created_at
on public.products(created_at);


create index if not exists idx_orders_user_id
on public.orders(user_id);


create index if not exists idx_orders_created_at
on public.orders(created_at);


create index if not exists idx_order_items_order_id
on public.order_items(order_id);


create index if not exists idx_order_items_product_id
on public.order_items(product_id);


/* =========================================================
   6. ENABLE ROW LEVEL SECURITY
========================================================= */

alter table public.products
enable row level security;

alter table public.profiles
enable row level security;

alter table public.orders
enable row level security;

alter table public.order_items
enable row level security;


/* =========================================================
   7. PRODUCTS POLICIES
========================================================= */


/*
   Semua pengunjung boleh melihat produk.
*/

drop policy if exists
"Public can read products"
on public.products;


create policy
"Public can read products"
on public.products

for select

to anon, authenticated

using (
    true
);


/*
   Admin boleh menambah produk.
*/

drop policy if exists
"Admin can insert products"
on public.products;


create policy
"Admin can insert products"
on public.products

for insert

to authenticated

with check (
    exists (
        select 1
        from public.profiles
        where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
);


/*
   Admin boleh mengubah produk.
*/

drop policy if exists
"Admin can update products"
on public.products;


create policy
"Admin can update products"
on public.products

for update

to authenticated

using (
    exists (
        select 1
        from public.profiles
        where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
)

with check (
    exists (
        select 1
        from public.profiles
        where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
);


/*
   Admin boleh menghapus produk.
*/

drop policy if exists
"Admin can delete products"
on public.products;


create policy
"Admin can delete products"
on public.products

for delete

to authenticated

using (
    exists (
        select 1
        from public.profiles
        where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
);


/* =========================================================
   8. PROFILE POLICIES
========================================================= */


/*
   User hanya dapat melihat profile miliknya.
*/

drop policy if exists
"Users can read own profile"
on public.profiles;


create policy
"Users can read own profile"
on public.profiles

for select

to authenticated

using (
    auth.uid() = id
);


/*
   User dapat membuat profile miliknya.
*/

drop policy if exists
"Users can insert own profile"
on public.profiles;


create policy
"Users can insert own profile"
on public.profiles

for insert

to authenticated

with check (
    auth.uid() = id
);


/*
   User dapat memperbarui profile miliknya.
*/

drop policy if exists
"Users can update own profile"
on public.profiles;


create policy
"Users can update own profile"
on public.profiles

for update

to authenticated

using (
    auth.uid() = id
)

with check (
    auth.uid() = id
);


/* =========================================================
   9. ORDERS POLICIES
========================================================= */


/*
   User hanya dapat melihat order miliknya.
*/

drop policy if exists
"Users can read own orders"
on public.orders;


create policy
"Users can read own orders"
on public.orders

for select

to authenticated

using (
    auth.uid() = user_id
);


/*
   Admin dapat melihat seluruh order.
*/

drop policy if exists
"Admin can read all orders"
on public.orders;


create policy
"Admin can read all orders"
on public.orders

for select

to authenticated

using (
    exists (
        select 1
        from public.profiles
        where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
);


/*
   Admin dapat memperbarui status/order.
*/

drop policy if exists
"Admin can update orders"
on public.orders;


create policy
"Admin can update orders"
on public.orders

for update

to authenticated

using (
    exists (
        select 1
        from public.profiles
        where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
)

with check (
    exists (
        select 1
        from public.profiles
        where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
);


/* =========================================================
   10. ORDER ITEMS POLICIES
========================================================= */


/*
   User hanya dapat melihat item dari order miliknya.
*/

drop policy if exists
"Users can read own order items"
on public.order_items;


create policy
"Users can read own order items"
on public.order_items

for select

to authenticated

using (
    exists (
        select 1
        from public.orders
        where orders.id = order_items.order_id
        and orders.user_id = auth.uid()
    )
);


/*
   Admin dapat melihat seluruh order items.
*/

drop policy if exists
"Admin can read all order items"
on public.order_items;


create policy
"Admin can read all order items"
on public.order_items

for select

to authenticated

using (
    exists (
        select 1
        from public.profiles
        where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
);


/* =========================================================
   11. CHECKOUT FUNCTION
   create_ardana_order
========================================================= */

drop function if exists
public.create_ardana_order(
    text,
    text,
    text,
    jsonb
);


create or replace function
public.create_ardana_order(
    p_customer_name text,
    p_phone text,
    p_notes text,
    p_items jsonb
)

returns jsonb

language plpgsql

security definer

set search_path = public

as $$

declare

    v_user_id uuid;

    v_order_id bigint;

    v_order_number text;

    v_total numeric(12, 2) := 0;

    v_item jsonb;

    v_product_id bigint;

    v_product_name text;

    v_price numeric(12, 2);

    v_quantity integer;

    v_stock integer;

    v_subtotal numeric(12, 2);

begin

    /* =====================================================
       CEK USER LOGIN
    ===================================================== */

    v_user_id := auth.uid();


    if v_user_id is null then

        raise exception
            'Kamu harus login terlebih dahulu.';

    end if;


    /* =====================================================
       VALIDASI CUSTOMER
    ===================================================== */

    if trim(coalesce(p_customer_name, '')) = '' then

        raise exception
            'Nama customer wajib diisi.';

    end if;


    if trim(coalesce(p_phone, '')) = '' then

        raise exception
            'Nomor WhatsApp wajib diisi.';

    end if;


    /* =====================================================
       VALIDASI CART
    ===================================================== */

    if p_items is null
       or jsonb_array_length(p_items) = 0 then

        raise exception
            'Keranjang masih kosong.';

    end if;


    /* =====================================================
       BUAT NOMOR ORDER
    ===================================================== */

    v_order_number :=
        'ARD-' ||
        to_char(
            now(),
            'YYYYMMDDHH24MISS'
        ) ||
        '-' ||
        floor(
            random() * 1000
        )::text;


    /* =====================================================
       INSERT ORDER AWAL
    ===================================================== */

    insert into public.orders (

        order_number,
        customer_name,
        phone,
        notes,
        total,
        status,
        user_id

    )

    values (

        v_order_number,
        trim(p_customer_name),
        trim(p_phone),
        nullif(
            trim(coalesce(p_notes, '')),
            ''
        ),
        0,
        'pending',
        v_user_id

    )

    returning id
    into v_order_id;


    /* =====================================================
       PROSES SETIAP ITEM
    ===================================================== */

    for v_item in
        select *
        from jsonb_array_elements(p_items)

    loop

        v_product_id :=
            (v_item ->> 'product_id')::bigint;


        v_quantity :=
            (v_item ->> 'quantity')::integer;


        if v_quantity is null
           or v_quantity <= 0 then

            raise exception
                'Jumlah produk tidak valid.';

        end if;


        /* =================================================
           LOCK PRODUCT
        ================================================= */

        select
            name,
            price,
            stock

        into
            v_product_name,
            v_price,
            v_stock

        from public.products

        where id = v_product_id

        for update;


        if not found then

            raise exception
                'Produk dengan ID % tidak ditemukan.',
                v_product_id;

        end if;


        /* =================================================
           CEK STOCK
        ================================================= */

        if v_stock < v_quantity then

            raise exception
                'Stock produk "%" tidak mencukupi.',
                v_product_name;

        end if;


        /* =================================================
           HITUNG SUBTOTAL
        ================================================= */

        v_subtotal :=
            v_price * v_quantity;


        v_total :=
            v_total + v_subtotal;


        /* =================================================
           SIMPAN ORDER ITEM
        ================================================= */

        insert into public.order_items (

            order_id,
            product_id,
            product_name,
            price,
            quantity,
            subtotal

        )

        values (

            v_order_id,
            v_product_id,
            v_product_name,
            v_price,
            v_quantity,
            v_subtotal

        );


        /* =================================================
           KURANGI STOCK
        ================================================= */

        update public.products

        set stock =
            stock - v_quantity

        where id = v_product_id;


    end loop;


    /* =====================================================
       UPDATE TOTAL ORDER
    ===================================================== */

    update public.orders

    set total = v_total

    where id = v_order_id;


    /* =====================================================
       RETURN RESULT
    ===================================================== */

    return jsonb_build_object(

        'success',
        true,

        'order_id',
        v_order_id,

        'order_number',
        v_order_number,

        'total',
        v_total

    );


exception

    when others then

        /*
           Jika terjadi error,
           seluruh transaksi akan rollback.
        */

        raise;

end;

$$;


/* =========================================================
   12. FUNCTION PERMISSION
========================================================= */


/*
   Hanya user yang sudah login
   yang dapat melakukan checkout.
*/

revoke all
on function
public.create_ardana_order(
    text,
    text,
    text,
    jsonb
)
from public;


grant execute
on function
public.create_ardana_order(
    text,
    text,
    text,
    jsonb
)
to authenticated;


/* =========================================================
   DATABASE SELESAI
========================================================= */